# Report 
Group 5 - Product in consideration Diacetyl (mmol/gDW/h)\
Guilherme Lobo\
Karyna Lysenko\
Rodrigo Esperança

Biologia de Sistemas - Universidade do Minho\
dezembro de 2022

### Documentação (apagar depois)
https://cobrapy.readthedocs.io/en/latest/

In [7]:
import cobra
from cobra.io import read_sbml_model
from cobra.flux_analysis import flux_variability_analysis as fva

In [4]:
model = read_sbml_model("sth.xml")
#model

In [1]:
# print(len(model.reactions))
# print(len(model.metabolites))
# print(len(model.genes))

In [29]:
#To find out the Diacetyl metabolite id
for i in model.metabolites:
    if i.name == "Diacetyl_":
        print(i.id)

diact_c
diact_e

In [31]:
model.metabolites.get_by_id("diact_c")

In [32]:
model.metabolites.get_by_id("diact_e")

In [7]:
DIACTt = model.reactions.get_by_id("DIACTt")
EX_diact_e = model.reactions.get_by_id("EX_diact_e")
DIACTt
#EX_diact_e

## Chemical defined medium (CDM)
### Function objetive: maximization of biomass production.

##### 1 a) What is the wild-type production of the compound?

In [49]:
#model.summary()

In [61]:
#model.optimize("diact_e")
#model.optimize.fluxes("diact_c")
model.optimize()["EX_diact_e"] #

0.0

In [63]:
model.metabolites.diact_e.summary()
# model.metabolites.diact_c.summary()

#### 1 b) Access the robustness of the presented solution using the Flux Variability Analysis approach.

In [64]:
#Result of FBA = 1.042 (units ?)
model_fva=fva(model,fraction_of_optimum=1)

In [66]:
model_fva.loc["EX_diact_e"] #maximo mto baixo, logo é como 0

minimum    0.000000e+00
maximum   -9.863691e-13
Name: EX_diact_e, dtype: float64

Conclusion:

#### 1 c) What are the maximum compound production capabilities, guaranteeing a minimum growth rate of 20% of the wild type?

In [ ]:
model.reactions.biomass_STR.lower_bound=0.2084
model.reactions.biomass_STR.upper_bound=1.042
model.optimize()

In [39]:
model.summary(fva=0.20)

#### 1 d) Evaluate if single gene deletions enhance the production of the compound. Rank the mutants obtained according to the compound production capacity and growth performance.

In [5]:
from cobra.flux_analysis import (single_gene_deletion, double_gene_deletion)

In [17]:
model = read_sbml_model("sth.xml")
# for i in model.genes:
    print(i)
print(len(model.genes))

476

In [22]:
abc=single_gene_deletion(model,model.genes)

In [32]:
print(abc.growth)

0      1.042253e+00
1      1.042253e+00
2      1.042253e+00
3      1.042253e+00
4      1.042253e+00
           ...
471    5.290879e-15
472    0.000000e+00
473    1.042253e+00
474    0.000000e+00
475    1.042253e+00
Name: growth, Length: 476, dtype: float64

In [38]:
for i in abc.growth:
    if i != (float('1.042253')):
        print(round(i))

1
1
1
1
1
1
1
1
1
1
1
0
1
0
1
1
1
1
1
1
1

ValueError: cannot convert float NaN to integer

In [ ]:
print(single_gene_deletion(model,model.genes).growth[0])

## Milk medium (MM)
### Function objetive: minimization of casein consumption while constraining the growth rate to 0.64 h-1

In [75]:
model.optimize()["EX_caspep_e"] #

0.0

In [88]:
#Duvida
model_milk = read_sbml_model("sth.xml")
model_milk.objective = 'EX_caspep_e' #colocar igual ao id anterior
model_milk.summary()

In [89]:
#não esquecer restringir o fluxo para upper.bound e under.bound = 0.64
model_milk.reactions.EX_caspep_e.lower_bound=0.64
model_milk.reactions.EX_caspep_e.upper_bound=0.64

#### 1 a) What is the wild-type production of the compound?

#### 1 b) Access the robustness of the presented solution using the Flux Variability Analysis approach.

#### 1 c) What are the maximum compound production capabilities, guaranteeing a minimum growth rate of 20% of the wild type?

#### 1 d) Evaluate if single gene deletions enhance the production of the compound. Rank the mutants obtained according to the compound production capacity and growth performance.