# Report 
Group 5 - Product in consideration Diacetyl (mmol/gDW/h)\
Guilherme Lobo\
Karyna Lysenko\
Rodrigo Esperança

Biologia de Sistemas - Universidade do Minho\
dezembro de 2022

### Documentação (apagar depois)
https://cobrapy.readthedocs.io/en/latest/

In [24]:
import cobra
from cobra.io import read_sbml_model
from cobra.flux_analysis import flux_variability_analysis as fva

In [4]:
model = read_sbml_model("sth.xml")
#model

In [1]:
# print(len(model.reactions))
# print(len(model.metabolites))
# print(len(model.genes))

In [29]:
#To find out the Diacetyl metabolite id
for i in model.metabolites:
    if i.name == "Diacetyl_":
        print(i.id)

diact_c
diact_e

In [31]:
model.metabolites.get_by_id("diact_c")

In [32]:
model.metabolites.get_by_id("diact_e")

In [7]:
DIACTt = model.reactions.get_by_id("DIACTt")
EX_diact_e = model.reactions.get_by_id("EX_diact_e")
DIACTt
#EX_diact_e

## Chemical defined medium (CDM)
### Function objetive: maximization of biomass production.

##### 1 a) What is the wild-type production of the compound?

In [38]:
model.summary()

In [12]:
model.metabolites.diact_e.summary()

#### 1 b) Access the robustness of the presented solution using the Flux Variability Analysis approach.

In [42]:
#Result of FBA = 1.042 (units ?)
model_fva=fva(model)

In [46]:
model_fva

               minimum   maximum
MANpts        0.000000  0.000000
PGGT2         0.129698  0.129698
AIRC          0.000000  0.010905
Kt2          -0.014540  0.014540
MOADCST       0.000000  0.000000
...                ...       ...
EX_sucr_e     0.000000  0.000000
FFSD          0.000000  0.000000
CASP          0.000000  0.000000
EX_caspepm_e  0.000000  0.000000
CASMabc       0.000000  0.000000

[656 rows x 2 columns]

In [45]:
model.optimize()

Conclusion:

#### 1 c) What are the maximum compound production capabilities, guaranteeing a minimum growth rate of 20% of the wild type?

In [ ]:
model.reactions.biomass_STR.lower_bound=0.2084
model.reactions.biomass_STR.upper_bound=1.042
model.optimize()

In [39]:
model.summary(fva=0.20)

#### 1 d) Evaluate if single gene deletions enhance the production of the compound. Rank the mutants obtained according to the compound production capacity and growth performance.

## Milk medium (MM)
### Function objetive: minimization of casein consumption while constraining the growth rate to 0.64 h-1

In [ ]:
#Duvida
model_milk = read_sbml_model("sth.xml")
with model_milk:
    model_milk.objective = {model_milk.reactions.biomass_STR: 1}
    model_milk.optimize()
    print(model_milk.reactions.biomass_STR.flux)

#### 1 a) What is the wild-type production of the compound?

#### 1 b) Access the robustness of the presented solution using the Flux Variability Analysis approach.

#### 1 c) What are the maximum compound production capabilities, guaranteeing a minimum growth rate of 20% of the wild type?

#### 1 d) Evaluate if single gene deletions enhance the production of the compound. Rank the mutants obtained according to the compound production capacity and growth performance.